import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Provider from "./provider.js";
import { ClerkProvider } from "@clerk/nextjs";
import UserSync from "./UserSync"; // ✅ ১. এই ফাইলটি ইম্পোর্ট করুন

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Mirhas Magic Studio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <ClerkProvider>
          <Provider>
            <UserSync /> {/* ✅ ২. এই লাইনটি এখানে বসিয়ে দিন */}
            {children}
          </Provider>
        </ClerkProvider>
      </body>
    </html>
  );
}